# Generated by Django 4.2.18 on 2025-01-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_contact_message_id_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AlterField(
            model_name='car',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
            preserve_default=False,
        ),
    ]
