# Generated by Django 4.2.18 on 2025-01-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_car_image_alter_car_age_alter_car_car_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='car/images/'),
            preserve_default=False,
        ),
    ]
